### ISSUE TITLE
More about the installation

### ISSUE THREAD

**Issue by morkin1792** [Split7fire/linux_on_chuwi_hibook#1]
Can you write more about the installation? I was try put the Manjaro in my Hibook and I was compile the linux 4.12.4 with various modules including some listed, but the touchscreen, power controller and wifi don't recognized.

**Comment by Split7fire** [comment]
No special installation was needed. 

- Regarding

 touchscreen, you should better to read https://github.com/onitake/gsl-firmware

- As for power controller - no special requirements needed. Just recompile kernel with AXP modules built-in.
- Wi-Fi firmware need to be in place, as I mentioned on start page.

**Comment by gschuurman** [comment]
Would you be able to share your bios settings?
I cant get ajustable brightness to work this crashes with: 
`[    2.685700] [drm:pwm_setup_backlight [i915]] *ERROR* Failed to own the pwm chip
` 
and the touchscreen errors out with the follwowing while loading the module with insmod:
`[  388.272885] gslx680_ts_acpi: loading out-of-tree module taints kernel.
[  388.273151] gslx680_ts_acpi: module verification failed: signature and/or required key missing - tainting kernel
[  388.283151] gslx680 i2c-MSSL0017:00: gsl_ts_probe: got a device named MSSL0017:00 at address 0x40, IRQ 184, flags 0x0
[  388.287359] input: Silead GSLx680 Touchscreen as /devices/pci0000:00/808622C1:05/i2c-13/i2c-MSSL0017:00/input/input10
[  389.306916] gpio gpiochip1: (INT33FF:01): gpiochip_lock_as_irq: tried to flag a GPIO set as output for IRQ
[  389.306936] gpio gpiochip1: (INT33FF:01): unable to lock HW IRQ 13 for IRQ
[  389.306947] genirq: Failed to request resources for MSSL0017:00 (irq 184) on irqchip chv-gpio
[  389.307872] gslx680 i2c-MSSL0017:00: gsl_ts_probe: failed to register interrupt
[  389.507812] gslx680: probe of i2c-MSSL0017:00 failed with error -22
`

I'm using ubuntu 17 with kernel  `4.12.0-041200-generic #201707022031 SMP Mon Jul 3 00:32:52 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by morkin1792** [comment]
About the WiFi, I'm don't understand where I'm find the firmware.

**Comment by gschuurman** [comment]
https://github.com/hadess/rtl8723bs
Just download the repo and run make in the folder with the makefiles, then just reboot and you've got yourself working WiFi.

**Comment by Split7fire** [comment]
@g-crash nope, since 4.12 rtl8723bs have in-tree driver. So you need only firmware. I borrow from [here](https://yadi.sk/d/LbaBpYVuqYfCy)

**Comment by gschuurman** [comment]
If you look at the makefile you will see it just copies the firmware with the make install command. It only automates your process.

**Comment by gschuurman** [comment]
@Split7fire I'm still struggling with my screen backlight and the touchscreen, do you have ajustable backlight working? And do you have any ideas what is wrong with my touchscreen?

**Comment by Split7fire** [comment]
@g-crash, I managed to install hadess driver earlier, but firmware still was needed.
I haven't got linux on my Chuwi now, because of infrequent lock-ups. I don't remember any backlight-specific configuration.

**Comment by morkin1792** [comment]
@g-crash maybe one solution by the backlight be the xrandr (eg: xrandr --brightness 0.8)
@Split7fire thanks, can close the issue. I'm go try later (until november) and anything I ask for your help again.

**Comment by gschuurman** [comment]
Thanks this is a workaround for now. if i find the solution to the pwm chip issue i'll inform you as well.
