### ISSUE TITLE
still no sound

### ISSUE THREAD

**Issue by Ygarr** [Split7fire/linux_on_chuwi_hibook#2]
I am using Ubuntu 17.10
But no sound
Just tried LIVE Fedora 27 on Chuwi - but no sound still. What to do to have sound in headphones at least?

Is there any working configs to compare?

**Comment by Ygarr** [comment]
N.B.
~pacmd list-cards
1 card(s) available.
    index: 0
	name: <alsa_card.platform-bytcr_rt5651>
	driver: <module-alsa-card.c>
	owner module: 6
	properties:
		alsa.card = "0"
		alsa.card_name = "bytcr-rt5651"
		alsa.long_card_name = "Hampoo-Defaultstring-Defaultstring-CherryTrailCR"
		alsa.driver_name = "snd_soc_sst_bytcr_rt5651"
		device.bus_path = "platform-bytcr_rt5651"
		sysfs.path = "/devices/pci0000:00/808622A8:00/bytcr_rt5651/sound/card0"
		device.form_factor = "internal"
		device.string = "0"
		device.description = "Built-in Audio"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card"
	profiles:
		HiFi: Play HiFi quality Music (priority 8000, available: unknown)
		off: Off (priority 0, available: unknown)
	active profile: <HiFi>
	sinks:
		alsa_output.platform-bytcr_rt5651.HiFi__hw_bytcrrt5651__sink/#1: Built-in Audio Speaker playback + Headphones playback
	sources:
		alsa_output.platform-bytcr_rt5651.HiFi__hw_bytcrrt5651__sink.monitor/#1: Monitor of Built-in Audio Speaker playback + Headphones playback
	ports:
		[Out] Speaker: Speaker playback (priority 100, latency offset 0 usec, available: unknown)
			properties:
				
		[Out] Headphones: Headphones playback (priority 100, latency offset 0 usec, available: unknown)
			properties:

**Comment by Ygarr** [comment]
inxi -A
Audio:     Card bytcr-rt5651 driver: bytcr-rt5651
           Sound: Advanced Linux Sound Architecture v: k4.14.2-041402-generic

**Comment by Split7fire** [comment]
You need to **install** Fedora 27 and **fully update**, because in a recent update they repair intel hdmi module, which cause pulseaudio to crash constantly. After that you can see in gnome audio settings 2 audio outputs.

**Comment by Ygarr** [comment]
Thank You a lot. Also Arch user said, that headphones are working.  But in live cd mode I get Arch without sound too. 
I also tried nice chinese PhoenixOS, there was also no sound.


Then from same github (UCM) 8 days ago were commited new configs for bytcr-rt5651. And it helps me. 
Now on my Ubuntu Mate 17.10 with kernel 4.14.4 I have sound in headphones.

But one thing disappoints me: qpaeq AKA pulseaudio-equalizer does not work. 

Do You have working equalizer in Fedora?

**Comment by Split7fire** [comment]
nope, I don't have to. Why you are using it?

**Comment by Ygarr** [comment]
To compensate for the lack of sound from the weak speakers of the laptop and also the sound from the headphones

**Comment by Split7fire** [comment]
@Ygarr "weak **external** speakers"?

**Comment by Ygarr** [comment]
Well, I have a variety of devices. So this option is also possible

**Comment by Split7fire** [comment]
ok, closing issue.
